/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface SdPartRequest {
  'id' : string,
  'customerName' : string,
  'status' : string,
  'partPhotoUrl' : string,
  'caseDbId' : string,
  'rejectedReason' : string,
  'rejectedByName' : string,
  'partCode' : string,
  'partName' : string,
  'productType' : string,
  'cancelledAt' : string,
  'cancelledBy' : string,
  'rejectedAt' : string,
  'rejectedBy' : string,
  'message' : string,
  'technicianId' : string,
  'companyName' : string,
  'issuedByName' : string,
  'priority' : string,
  'caseId' : string,
  'issuedAt' : string,
  'issuedBy' : string,
  'cancelledByName' : string,
  'requestedByName' : string,
  'requestedAt' : string,
  'requestedBy' : string,
}
export interface SdUser {
  'id' : string,
  'status' : string,
  'password' : string,
  'name' : string,
  'createdAt' : string,
  'role' : string,
  'email' : string,
  'phone' : string,
  'lastLogin' : string,
}
export interface _SERVICE {
  'approveSdUser' : ActorMethod<[string], undefined>,
  'cancelSdPartRequest' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'clearAllData' : ActorMethod<[], undefined>,
  'createSdPartRequest' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    SdPartRequest
  >,
  'createSdUser' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    SdUser
  >,
  'deleteSdPartRequest' : ActorMethod<[string], undefined>,
  'deleteSdUser' : ActorMethod<[string], undefined>,
  'editSdUser' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'getAIInsights' : ActorMethod<[string], string>,
  'getAIInsightsCache' : ActorMethod<[], string>,
  'getAIInsightsCacheTime' : ActorMethod<[], bigint>,
  'getMidnightTaskRanDate' : ActorMethod<[], string>,
  'getSdAppDataJson' : ActorMethod<[], string>,
  'getSdCasesJson' : ActorMethod<[], Array<string>>,
  'getSdInventoryJson' : ActorMethod<[], string>,
  'getSdNoticesJson' : ActorMethod<[], Array<string>>,
  'getSdPartRequests' : ActorMethod<[], Array<SdPartRequest>>,
  'getSdPartRequestsJson' : ActorMethod<[], string>,
  'getSdPartRequestsV2Json' : ActorMethod<[], string>,
  'getSdUsers' : ActorMethod<[], Array<SdUser>>,
  'getSdUsersJson' : ActorMethod<[], string>,
  'initSeedUsers' : ActorMethod<[], undefined>,
  'issueSdPartRequest' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'loginSdUser' : ActorMethod<[string, string], [] | [SdUser]>,
  'rejectSdPartRequest' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'rejectSdUser' : ActorMethod<[string], undefined>,
  'setAIInsightsCache' : ActorMethod<[string], undefined>,
  'setAIInsightsCacheTime' : ActorMethod<[bigint], undefined>,
  'setMidnightTaskRanDate' : ActorMethod<[string], undefined>,
  'setSdAppData' : ActorMethod<[string], undefined>,
  'setSdAppDataJson' : ActorMethod<[string], undefined>,
  'setSdCases' : ActorMethod<[string], undefined>,
  'setSdCasesJson' : ActorMethod<[Array<string>], undefined>,
  'setSdInventory' : ActorMethod<[string], undefined>,
  'setSdInventoryJson' : ActorMethod<[string], undefined>,
  'setSdNotices' : ActorMethod<[string], undefined>,
  'setSdNoticesJson' : ActorMethod<[Array<string>], undefined>,
  'setSdPartRequestsJson' : ActorMethod<[string], undefined>,
  'setSdPartRequestsV2Json' : ActorMethod<[string], undefined>,
  'setSdUsersJson' : ActorMethod<[string], undefined>,
  'updateSdUserLogin' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];