/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SdUser {
    id: string;
    status: string;
    password: string;
    name: string;
    createdAt: string;
    role: string;
    email: string;
    phone: string;
    lastLogin: string;
}
export interface SdPartRequest {
    id: string;
    customerName: string;
    status: string;
    partPhotoUrl: string;
    caseDbId: string;
    rejectedReason: string;
    rejectedByName: string;
    partCode: string;
    partName: string;
    productType: string;
    cancelledAt: string;
    cancelledBy: string;
    rejectedAt: string;
    rejectedBy: string;
    message: string;
    technicianId: string;
    companyName: string;
    issuedByName: string;
    priority: string;
    caseId: string;
    issuedAt: string;
    issuedBy: string;
    cancelledByName: string;
    requestedByName: string;
    requestedAt: string;
    requestedBy: string;
}
export interface backendInterface {
    approveSdUser(userId: string): Promise<void>;
    cancelSdPartRequest(id: string, cancelledBy: string, cancelledByName: string, cancelledAt: string): Promise<void>;
    clearAllData(): Promise<void>;
    createSdPartRequest(id: string, caseId: string, caseDbId: string, customerName: string, partName: string, partCode: string, partPhotoUrl: string, requestedBy: string, requestedByName: string, requestedAt: string, message: string, productType: string, companyName: string, priority: string): Promise<SdPartRequest>;
    createSdUser(id: string, name: string, email: string, password: string, phone: string, role: string, status: string, createdAt: string): Promise<SdUser>;
    deleteSdPartRequest(id: string): Promise<void>;
    deleteSdUser(userId: string): Promise<void>;
    editSdUser(userId: string, name: string, email: string, phone: string, role: string, password: string): Promise<void>;
    getAIInsights(contextJson: string): Promise<string>;
    getAIInsightsCache(): Promise<string>;
    getAIInsightsCacheTime(): Promise<bigint>;
    getMidnightTaskRanDate(): Promise<string>;
    getSdAppDataJson(): Promise<string>;
    getSdCasesJson(): Promise<Array<string>>;
    getSdInventoryJson(): Promise<string>;
    getSdNoticesJson(): Promise<Array<string>>;
    getSdPartRequests(): Promise<Array<SdPartRequest>>;
    getSdPartRequestsJson(): Promise<string>;
    getSdPartRequestsV2Json(): Promise<string>;
    getSdUsers(): Promise<Array<SdUser>>;
    getSdUsersJson(): Promise<string>;
    initSeedUsers(): Promise<void>;
    issueSdPartRequest(id: string, technicianId: string, issuedAt: string, issuedBy: string, issuedByName: string): Promise<void>;
    loginSdUser(email: string, password: string): Promise<SdUser | null>;
    rejectSdPartRequest(id: string, reason: string, rejectedAt: string, rejectedBy: string, rejectedByName: string): Promise<void>;
    rejectSdUser(userId: string): Promise<void>;
    setAIInsightsCache(data: string): Promise<void>;
    setAIInsightsCacheTime(ts: bigint): Promise<void>;
    setMidnightTaskRanDate(date: string): Promise<void>;
    setSdAppData(jsonBlob: string): Promise<void>;
    setSdAppDataJson(jsonBlob: string): Promise<void>;
    setSdCases(jsonBlob: string): Promise<void>;
    setSdCasesJson(json: Array<string>): Promise<void>;
    setSdInventory(jsonBlob: string): Promise<void>;
    setSdInventoryJson(jsonBlob: string): Promise<void>;
    setSdNotices(jsonBlob: string): Promise<void>;
    setSdNoticesJson(json: Array<string>): Promise<void>;
    setSdPartRequestsJson(jsonBlob: string): Promise<void>;
    setSdPartRequestsV2Json(json: string): Promise<void>;
    setSdUsersJson(json: string): Promise<void>;
    updateSdUserLogin(userId: string, loginTime: string): Promise<void>;
}
import type { SdUser as _SdUser } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async approveSdUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveSdUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveSdUser(arg0);
            return result;
        }
    }
    async cancelSdPartRequest(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelSdPartRequest(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelSdPartRequest(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async clearAllData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllData();
            return result;
        }
    }
    async createSdPartRequest(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string, arg11: string, arg12: string, arg13: string): Promise<SdPartRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.createSdPartRequest(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSdPartRequest(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
            return result;
        }
    }
    async createSdUser(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<SdUser> {
        if (this.processError) {
            try {
                const result = await this.actor.createSdUser(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSdUser(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async deleteSdPartRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSdPartRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSdPartRequest(arg0);
            return result;
        }
    }
    async deleteSdUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSdUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSdUser(arg0);
            return result;
        }
    }
    async editSdUser(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editSdUser(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editSdUser(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async getAIInsights(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAIInsights(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAIInsights(arg0);
            return result;
        }
    }
    async getAIInsightsCache(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAIInsightsCache();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAIInsightsCache();
            return result;
        }
    }
    async getAIInsightsCacheTime(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAIInsightsCacheTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAIInsightsCacheTime();
            return result;
        }
    }
    async getMidnightTaskRanDate(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMidnightTaskRanDate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMidnightTaskRanDate();
            return result;
        }
    }
    async getSdAppDataJson(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSdAppDataJson();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSdAppDataJson();
            return result;
        }
    }
    async getSdCasesJson(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSdCasesJson();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSdCasesJson();
            return result;
        }
    }
    async getSdInventoryJson(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSdInventoryJson();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSdInventoryJson();
            return result;
        }
    }
    async getSdNoticesJson(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSdNoticesJson();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSdNoticesJson();
            return result;
        }
    }
    async getSdPartRequests(): Promise<Array<SdPartRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSdPartRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSdPartRequests();
            return result;
        }
    }
    async getSdPartRequestsJson(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSdPartRequestsJson();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSdPartRequestsJson();
            return result;
        }
    }
    async getSdPartRequestsV2Json(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSdPartRequestsV2Json();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSdPartRequestsV2Json();
            return result;
        }
    }
    async getSdUsers(): Promise<Array<SdUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSdUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSdUsers();
            return result;
        }
    }
    async getSdUsersJson(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSdUsersJson();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSdUsersJson();
            return result;
        }
    }
    async initSeedUsers(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initSeedUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSeedUsers();
            return result;
        }
    }
    async issueSdPartRequest(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.issueSdPartRequest(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.issueSdPartRequest(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async loginSdUser(arg0: string, arg1: string): Promise<SdUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginSdUser(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginSdUser(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectSdPartRequest(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectSdPartRequest(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectSdPartRequest(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async rejectSdUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectSdUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectSdUser(arg0);
            return result;
        }
    }
    async setAIInsightsCache(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAIInsightsCache(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAIInsightsCache(arg0);
            return result;
        }
    }
    async setAIInsightsCacheTime(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAIInsightsCacheTime(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAIInsightsCacheTime(arg0);
            return result;
        }
    }
    async setMidnightTaskRanDate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMidnightTaskRanDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMidnightTaskRanDate(arg0);
            return result;
        }
    }
    async setSdAppData(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSdAppData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSdAppData(arg0);
            return result;
        }
    }
    async setSdAppDataJson(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSdAppDataJson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSdAppDataJson(arg0);
            return result;
        }
    }
    async setSdCases(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSdCases(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSdCases(arg0);
            return result;
        }
    }
    async setSdCasesJson(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSdCasesJson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSdCasesJson(arg0);
            return result;
        }
    }
    async setSdInventory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSdInventory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSdInventory(arg0);
            return result;
        }
    }
    async setSdInventoryJson(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSdInventoryJson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSdInventoryJson(arg0);
            return result;
        }
    }
    async setSdNotices(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSdNotices(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSdNotices(arg0);
            return result;
        }
    }
    async setSdNoticesJson(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSdNoticesJson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSdNoticesJson(arg0);
            return result;
        }
    }
    async setSdPartRequestsJson(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSdPartRequestsJson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSdPartRequestsJson(arg0);
            return result;
        }
    }
    async setSdPartRequestsV2Json(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSdPartRequestsV2Json(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSdPartRequestsV2Json(arg0);
            return result;
        }
    }
    async setSdUsersJson(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSdUsersJson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSdUsersJson(arg0);
            return result;
        }
    }
    async updateSdUserLogin(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSdUserLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSdUserLogin(arg0, arg1);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SdUser]): SdUser | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
